### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by Sabayonte** [detectivekaktus/bridgewatcher#1]
I feel like a toddler right now xd

**Comment by detectivekaktus** [comment]
Hello there! I am glad you found my project and got interested in it!

I added `How do I get this to work` section in the `README.md` file in the root directory.

Right now the bot works only for the EU server, which I am going to fix very soon with new updates. Thank you!

**Comment by Sabayonte** [comment]
Sorry for renewing the "issue" but thank you so much for the work ❤
