### ISSUE TITLE
Can’t recognise item’s name

### ISSUE THREAD

**Issue by DerWinterhaus** [detectivekaktus/bridgewatcher#4]
Kept saying that the name’s wrong although it’s not the case
![IMG_1070](https://github.com/detectivekaktus/bridgewatcher/assets/92819519/e4709b52-16e7-45bd-bc7e-0c6ce3bf8c92)

**Comment by DerWinterhaus** [comment]
![IMG_1071](https://github.com/detectivekaktus/bridgewatcher/assets/92819519/53df2412-9648-458c-ae1c-19e532f03186)
somehow it can recognise rough stone, though

**Comment by detectivekaktus** [comment]
Hello there! I'm glad you submitted an issue to help other bot's users.

Can you provide the full command you sent to the bot?

**Comment by DerWinterhaus** [comment]
> Can you provide the full command you sent to the bot?
> 
![IMG_1073](https://github.com/detectivekaktus/bridgewatcher/assets/92819519/79409aa2-1d19-4c58-b937-369132bb3049)

> And here’s the result as of July 5th
![IMG_1074](https://github.com/detectivekaktus/bridgewatcher/assets/92819519/546d153e-1ee0-43e8-8c7c-2b277818a5cd)

**Comment by detectivekaktus** [comment]
I tried to involve some debugging on different servers, including some discord servers and Albion Online servers the bot offer but all my effort wasn't successful to figure out the problem you're currently having.

May I ask you to add me in discord? Username: detectivekaktus
